### ISSUE TITLE
Feed server outages into GitHub as critical issues

### ISSUE THREAD

**Issue by brettneese** [HBKEngineering/tracky-aws#1]
_From @brettneese on September 19, 2016 21:12_

https://hbkengineering.slack.com/archives/technical/p1474317197000281

This would allow the same kind of audit log around server issues as we get with code issues.

Could add such things as links to relevant Slack discussions, AWS notifications, and other logs.

_Copied from original issue: HBKEngineering/HBKApps#3_

**Comment by mnaughto** [comment]
This seems unnecessary.
